# Generated by Django 5.0.4 on 2024-04-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0002_tag_quote_created_at_alter_quote_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author',
            new_name='author_id',
        ),
    ]
