# Generated by Django 5.0.4 on 2024-04-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0003_rename_author_quote_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author_id',
            new_name='author',
        ),
    ]
